default:
  ALLOWED_HOSTS: [ ]
  DATABASE_URL: ""
  DIRS_EXCLUDED:
    - .idea
    - .pytest_cache
    - .static
    - .tests_artifacts
  DIRS_RESOURCES:
    - config
    - scripts
    - src/project/static/
    - src/applications/main/static/
    - src/applications/onboarding/static/
    - src/applications/profile/static/
  DIRS_SOURCES:
    - src
  DIRS_TEMPLATES:
    - src/project/templates/
    - src/applications/main/templates/
    - src/applications/onboarding/templates/
    - src/applications/profile/templates/
  DJANGO_SETTINGS_MODULE: "project.settings"
  MODE_DEBUG: true
  MODE_PROFILING: false
  HOST: ""
  PORT: -1
  PROJECT_NAME: ""
  SECRET_KEY: ""
  SENTRY_DSN: ""
  TEMPLATE_ENGINE: "Django"
  VENV_SYNTHETIC: false
  WEB_CONCURRENCY: 0


development:
  PORT: 8000
  HOST: "localhost"
  SECRET_KEY: "1"


ci:
  PORT: 8000
  SECRET_KEY: "1"
  WEB_CONCURRENCY: 2


heroku:
  DJANGO_SETTINGS_MODULE: "src.project.settings"
  HOST: ".herokuapp.com"
  MODE_DEBUG: false
  VENV_SYNTHETIC: true
